fail deployment when not 200 OK

diff --git a/.github/workflows/part_deploy_live.yml b/.github/workflows/part_deploy_live.yml
--- a/.github/workflows/part_deploy_live.yml
+++ b/.github/workflows/part_deploy_live.yml
@@ -41,6 +41,11 @@ jobs:
         id: pre-resolve
         run: echo "webhook_ip=$(dig +short servyy.bumbleflies.de)" >> "$GITHUB_OUTPUT"
       - name: Trigger deployment
-        run: curl -X POST ${{ secrets.WEBSITE_HOOK_URL }}/${{ secrets.WEBSITE_HOOK_SECRET }} --resolve 'webhook.bumbleflies.servyy.bumbleflies.de:443:${{ steps.pre-resolve.outputs.webhook_ip }}'
+        run: |
+          response=$(curl -s -o /dev/null -w "%{http_code}" -X POST ${{ secrets.WEBSITE_HOOK_URL }}/${{ secrets.WEBSITE_HOOK_SECRET }} --resolve 'webhook.bumbleflies.servyy.bumbleflies.de:443:${{ steps.pre-resolve.outputs.webhook_ip }}')
+          if [ "$response" -ne 200 ]; then
+            echo "Deployment trigger failed with status code $response"
+            exit 1
+          fi
     env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
